apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {APPNAME}-check
spec:
  inputs:
    resources:
      - name: {APPNAME}-gitsrc
        type: git
    params:
    - name: SONAR_HOST_URL
      description: Host URL where the sonarqube server is running
      default: ""
    - name: SONAR_PROJECT_KEY
      description: Project's unique key
      default: ""
  steps:
  - name: return-true
    image: registry.access.redhat.com/ubi8/ubi:latest
    workingDir: /workspace/{APPNAME}-gitsrc
    command: ["/bin/bash"]
    args:
      - -c
      - |
        set -e
        echo "No scan for now"
#  - name: sonar-scan
#    image: docker.io/sonarsource/sonar-scanner-cli:4.5@sha256:b8c95a37025f3c13162118cd55761ea0b2a13d1837f9deec51b7b6d82c52040a #tag: 4.5
#    workingDir: /workspace/{APPNAME}-gitsrc
#    command:
#      - sonar-scanner
