apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {APPNAME}-prod
spec:
  inputs:
    resources:
      - name: git-source-web
        type: git
      - name: docker-image-web
        type: image
    params:
      - name: pathToYamlFile
        description: The path to the yaml file to deploy within the git source
      - name: pathToDeployablesFile
        description: The path to the deployable file to deploy within the git source
  steps:
  - name: modify-app-deploy-yaml
    image: registry.access.redhat.com/ubi8/ubi:latest
    workingDir: /workspace/git-source-web
    command: ["/bin/bash"]
    args:
      - -c
      - |
        set -e
        SHORT_GIT_HASH="$(cat .git/FETCH_HEAD | awk '{print substr($1,0,7)}')"
        NEW_IMAGE_ID="$(inputs.resources.docker-image-web.url):$SHORT_GIT_HASH"
        echo "SHORT_GIT_HASH = $SHORT_GIT_HASH"
        echo "Using Image $NEW_IMAGE_ID"
        sed -i -e 's|__IMAGE__|'"$NEW_IMAGE_ID"'|g' /workspace/git-source-web/$(inputs.params.pathToYamlFile)/deployment.yaml
        sed -i -e 's|__IMAGE__|'"$NEW_IMAGE_ID"'|g' /workspace/git-source-web/$(inputs.params.pathToYamlFile)/deployable.yaml
  - name: deploy-image
    image: ibmgaragetsa/cpeir-runtime:v0.001
    command: ["/bin/bash"]
    args:
        - "-c"
        - |
          set -e
          oc apply -f /workspace/git-source-web/$(inputs.params.pathToYamlFile)/deployable.yaml
